-- MySQL Script generated by MySQL Workbench
-- Fri May  1 16:20:17 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`room_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room_type` (
  `room_type_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(500) NULL,
  `capacity` INT NOT NULL,
  `price_per_night` FLOAT NOT NULL,
  PRIMARY KEY (`room_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `floor` INT NULL,
  `room_type_id` INT NOT NULL,
  `room_number` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`room_id`),
  UNIQUE INDEX `room_number_UNIQUE` (`room_number` ASC) VISIBLE,
  CONSTRAINT `fk_room_room_type1`
    FOREIGN KEY (`room_type_id`)
    REFERENCES `mydb`.`room_type` (`room_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `booking_start` DATETIME NOT NULL,
  `booking_end` DATETIME NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `room_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `hasBreakfast` TINYINT NOT NULL,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_order_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media` (
  `media_id` INT NOT NULL,
  `path` VARCHAR(500) NULL,
  `title` VARCHAR(500) NULL,
  `description` VARCHAR(500) NULL,
  `alt_text` VARCHAR(500) NULL,
  `sort_helper` INT NULL,
  PRIMARY KEY (`media_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room_type_has_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room_type_has_media` (
  `room_type_room_type_id` INT NOT NULL,
  `media_media_id` INT NOT NULL,
  PRIMARY KEY (`room_type_room_type_id`, `media_media_id`),
  CONSTRAINT `fk_room_type_has_media_room_type1`
    FOREIGN KEY (`room_type_room_type_id`)
    REFERENCES `mydb`.`room_type` (`room_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_type_has_media_media1`
    FOREIGN KEY (`media_media_id`)
    REFERENCES `mydb`.`media` (`media_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room_extra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room_extra` (
  `room_extra_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `icon_key` VARCHAR(255) NULL,
  PRIMARY KEY (`room_extra_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room_extra_has_room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room_extra_has_room` (
  `room_extra_room_extra_id` INT NOT NULL,
  `room_room_id` INT NOT NULL,
  PRIMARY KEY (`room_extra_room_extra_id`, `room_room_id`),
  CONSTRAINT `fk_room_extra_has_room_room_extra1`
    FOREIGN KEY (`room_extra_room_extra_id`)
    REFERENCES `mydb`.`room_extra` (`room_extra_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_extra_has_room_room1`
    FOREIGN KEY (`room_room_id`)
    REFERENCES `mydb`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
